[package]
name = "sonnerie"
version = "0.5.0"
authors = ["Charles Samuels <kalle@eventures.vc>", "e.ventures Management LLC"]
edition = "2018"
description = "An easy timeseries database"
license = "BSD-2-Clause"
readme = "README.md"
repository = "https://github.com/njaard/sonnerie"
keywords = ["cli", "timeseries", "database"]
documentation = "https://docs.rs/sonnerie/"

[dependencies]
twoway="0.2"
memmap="0.7"
byteorder="1"
clap="2"
lz4="1"
chrono="0.4"
regex="1"
fs2="0.4"
parking_lot="0.10"
crossbeam="0.7"
libc="0.2"
hyper = "0.13"
tokio={ version="0.2", features=["rt-threaded"] }
futures = { version="0.3" }
url="2"
shardio="0.5"
lines_from_request={ version="0.2.0", path="lines_from_request" }
tempfile = "3"
serde = "1"
serde_derive = "1"
escape_string = {version="0.1.0", path="escape_string"}
