[package]
name = "sonnerie"
version = "0.4.2"
authors = ["Charles Samuels <kalle@eventures.vc>", "e.ventures Management LLC"]
description = "An easy timeseries database"
license = "BSD-2-Clause"
readme = "README.md"
repository = "https://github.com/njaard/sonnerie"
keywords = ["cli", "timeseries", "database"]
documentation = "https://docs.rs/sonnerie/"
edition = "2018"

[dependencies]
rusqlite = "0.14.0"
clap = "2"
libc = "0.2.43"
byteorder = "1"
nix = "0.11"
range = "0.3.1"
antidote = "1"
chrono = "0.4.6"
intrusive-collections = "0.7.5"
rustyline = "2"
shlex = "0.1.1"
sonnerie-api = {version="0.4.1", path="sonnerie-api"}
escape_string = {version="0.1.0", path="escape_string"}
linestream = {version="0.1.0", path="linestream"}
daemonize= "0.3"

[dev-dependencies]
tempfile = "3"
