[package]
name = "escape_string"
version = "0.1.0"
authors = ["Charles Samuels <kalle@eventures.vc>"]
license = "BSD-2-Clause"
description = "Very efficiently parse backslash-escaped strings"

[dependencies]
